### ISSUE TITLE
post merge issue of PR "Reduction in Composable Kernel #82"

### ISSUE THREAD

**Issue by asroy** [ROCmSoftwarePlatform/composable_kernel#104]
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/82/files#r813365665
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/82/files#r817995966
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/82/files#r815560085
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/82#discussion_r815566533
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/82#discussion_r815565337
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/82#discussion_r815565508
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/82#discussion_r818020743
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/82/files#r820111066
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/82/files#r820111326
- [ ] Add ctest
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/115#issuecomment-1063664660

**Comment by qianfengz** [comment]
Also, I want to change the DeviceReduceXXXX class from using `index_t Rank,  typename ReduceDims` to `index_t Rank, index_t NumReduceDims` to move the `ReduceDims` from template argument to runtime parameters,  so that more compiling time can be saved and more Reduction cases can be supported.

**Comment by qianfengz** [comment]
[PR.105](https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/115)  pushed for the issue
