### ISSUE TITLE
There is a backward data error when filter is 1x1 and stride=2

### ISSUE THREAD

**Issue by ltqin** [ROCmSoftwarePlatform/composable_kernel#105]
if filter is 1x1 and  stride = 2, backward data can not pass the verification.
example config:
./build/bin/conv2d_bwd_data_xdl 1 2 1 256 64 128 1 1 2 2 2 2 1 1 0 0 0 0

**Comment by ltqin** [comment]
code bug, created pr: https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/132

**Comment by asroy** [comment]
@ltqin Please update if this bug still exisits?

**Comment by ltqin** [comment]
already fixed
