### ISSUE TITLE
Post Merge Issue of PR #106

### ISSUE THREAD

**Issue by asroy** [ROCmSoftwarePlatform/composable_kernel#110]
- [x] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/106#discussion_r820027446
- [x] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/106#discussion_r820027607
- [x] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/106#discussion_r820027624
- [x] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/106#discussion_r820027660
- [x] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/106#discussion_r820027671
- [x] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/106#discussion_r820027697
- [x] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/106#discussion_r820027776
- [x] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/106#discussion_r820027814

**Comment by ltqin** [comment]
https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/114
