### ISSUE TITLE
Possible bug in reduction

### ISSUE THREAD

**Issue by j4yan** [ROCmSoftwarePlatform/composable_kernel#121]
This branch https://github.com/ROCmSoftwarePlatform/composable_kernel/tree/reproduce_error_in_reduction is based on https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/118. I inserted some static assertion to `ThreadwiseTensorSliceTransfer_v1r3` which causes the reduction compile to fail.

This may exposure a potential debug in reduction: The compile log shows that `SliceLengths = Sequence{1}`, and `DstScalarPerVector=2`. 

On latest develop branch (827301d95af93) we have exactly the same issue.

**Comment by j4yan** [comment]
@qianfengz @asroy

**Comment by j4yan** [comment]
TOOD: add static_assert to threadwise copy constructor.

**Comment by qianfengz** [comment]
@j4yan  Thank you for the finding.    There is 1 or 2 buggy configuration in each of my following files which define the configurations:
1. device_reduce_instance_blockwise.hpp
2. device_reduce_instance_threadwise.hpp
3. device_reduce_instance_mutiblock_atomic_add.hpp
4. device_reduce_instance_multiblock_partial_reduce.hpp
5. device_reduce_instance_blockwise_second_call.hpp

With these buggy configurations, the MThreadSliceSize could not be completely divided by the OurDstVectorSize. This is a obvious bug, but could be easily ignored by myself, and it could cause GPU memory fault without being corrected.  
I found that after fixing these wrong configurations,  some "GPU memory fault" which has occurred with my "int8" reduction cases can be removed.   
The fixing as well as the static_assert are added in my branch ck_reduce_int8_bf16, this will be pulled very soon.

**Comment by qianfengz** [comment]
The issue is solved by [47d5](https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/125/commits/6a0afa585cbe37640ecf345b5f53978de72947d5)
And the static_asserts are added by [4a53](https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/125/commits/48a931dc770829e659bd9bab0abe62dde9234a53)
