### ISSUE TITLE
Batched GEMM performance issue

### ISSUE THREAD

**Issue by j4yan** [ROCmSoftwarePlatform/composable_kernel#139]
The new batched GEMM performance (develop cb87b049de8f8122e8a197) is ~2TFlops lower than the old one (b53e9d08ed5a9f80d8). This can be reproduced by running 

`./bin/ckProfiler batched_gemm 0 0 1 2 0 5 1024 512 2048 -1 -1 -1 8`

Other observations include:

1. Both versions have exactly the same number of s and v instructions and almost the same number of VGPRS in the main K0 loop.
2. The old version has scratch memory if `HasMainK0BlockLoop=true`; the new version does not.

**Comment by asroy** [comment]
Dropping this issue
