### ISSUE TITLE
Post-merge of PR #134

### ISSUE THREAD

**Issue by j4yan** [ROCmSoftwarePlatform/composable_kernel#147]
Unresolved comments:

- [x] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/134/files#r831587024
- [x] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/134/files#r831594716
- [x] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/134/files#
- [x] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/134/files#r831602013
- [x] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/134/files#r831543295
- [x] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/134/files#r831556295
- [x] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/134/files#r831549503
- [x] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/134/files#r831557682
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/134/files#r831558978
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/134/files#r831567999
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/134/files#r831568768
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/134/files#r831574274
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/134/files#r831575971
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/134#discussion_r831580173
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/134#discussion_r831585894
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/134#discussion_r831588112
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/134#discussion_r831589793
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/134#discussion_r831591111
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/134#discussion_r831594716
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/134#discussion_r831595668
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/134#discussion_r831597016
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/134#discussion_r831598150
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/134#discussion_r834464606

**Comment by j4yan** [comment]
@ltqin @asroy

**Comment by asroy** [comment]
conv code has been overhauled
