### ISSUE TITLE
Add compiler warning on comparing int and size_t

### ISSUE THREAD

**Issue by j4yan** [ROCmSoftwarePlatform/composable_kernel#153]
There are a lot of places where we are comparing `int` with `size_t`, which is risky. I suggest we turn on warnings of this, and get rid of them eventually.

**Comment by asroy** [comment]
what is the clang flag for this kind of warning?

**Comment by j4yan** [comment]
There are different flags controlling different warning on different comparisons. For this specific case, it's `-Wsign-compare`.
