### ISSUE TITLE
Use CMake options to replace macros in config.hpp

### ISSUE THREAD

**Issue by j4yan** [ROCmSoftwarePlatform/composable_kernel#169]
This is to follow up a discussion https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/130#discussion_r838692788

I suggest that the macros in config.hpp, at least those independent ones, are moved into cmake. This way users and developers do not need to change the code (ie, config.hpp) itself for different configurations.

**Comment by asroy** [comment]
no long pursued. deicided to not use cmake for code gen
