### ISSUE TITLE
backward data v4r1 have an issue on  rocm5.0

### ISSUE THREAD

**Issue by ltqin** [ROCmSoftwarePlatform/composable_kernel#173]
Convolution 1d and 2d  backward data v4r1  can pass the test(restnet50) on rocm4.0, but fail on rocm5.0.  and if we don't use buffer store, it can pass on rocm5.0, so we guess  this is a  compiler issue.   
Opened a compiler ticket on JIRA here: https://ontrack-internal.amd.com/browse/SWDEV-329795

**Comment by asroy** [comment]
@ltqin The JIRA only contains a single failure for them to triage and fix. But this github issue need to contain the complete list of failure, so when JRIA is fixed. We can come back to this github issue, and do a full examination.

**Comment by ltqin** [comment]
test on 9110:
1d conv:
fp32 pass 
fp16 pass
bf16 pass
int8:
one config and one tunning parameter fail:
config:128 64 256 1 56 1 1 0 0
turning parameter:DeviceConvndBwdDataXdl_Input_N_Di_Hi_Wi_C_Weight_K_Z_Y_X_C_Output_N_Do_Ho_Wo_K<256, 128, 256, 4>

**Comment by ltqin** [comment]
remove buffer store on 9110

- 1d
- 2d
fp32: pass
fp16: pass
bf16: pass
int8:fail
filter1x1strid1pad0:
GridSize_M_N_K0_K1<256, 256, 128, 4, 16>
- 3d

**Comment by ltqin** [comment]
on rocm4.0:

- 1d
fp32: pass
fp16: pass
bf16: pass
int8: pass

- 2d
fp32: pass
fp16: pass
bf16: pass
int8:fail
only one config fails:
128 64 256 1 1 56 56 1 1 1 1 0 0 0 0
<256, 128, 256, 4> Filter1x1Stride1Pad0

**Comment by zjing14** [comment]
@ltqin Please wrap all failures configs above into ckProfiler commands and update JIRAs.

**Comment by ltqin** [comment]
done

**Comment by ltqin** [comment]
test can pass with rocm5.1, so create a PR for adding bwd data test
https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/234

**Comment by ltqin** [comment]
rocm5.1 fix this issue
