### ISSUE TITLE
Use ck::half_t instead of half_float::half on host, so we can remove dependency on half_float::half in future

### ISSUE THREAD

**Issue by rocking5566** [ROCmSoftwarePlatform/composable_kernel#193]
Since `numeric_limits<ck::half_t>::lowest()` will get 0.
if all the value in input tensor is negative, ReductionHost will get 0

**Comment by qianfengz** [comment]
Host Reduction need use  `half_float::half`.  The reason that Host Reduction does not choose to use `ck::half_t (_Float16)` is that the HIP provided math functions in file `/opt/rocm/hip/include/hip/hcc_detail/amd_hip_fp16.h`, for example,  `__hisnan, __hsqrt, __habs`  can only be used in `__device`__ mode.  By using `half_float::half`,  Host Reduction can very well take advantage of well implemented maths in `half.hpp`.
In the other hand,  for the kernel side to use `ck::half_t`,  we overloaded `NumericLimits` class in `data_type.hpp` to provide numeric limits lie `lowest()`, `min()`, `max()`

**Comment by asroy** [comment]
@qianfengz Please don't use ```std:: numeric_limits``` in host or device code, use ```ck::NumericLimits<ck::half_t>``` on host as well.

At some point, we would add all math function for ```ck::half_t``` for host too, and remove dependency on ```half_float::half``` even on host. Because unlike MIOpen, CK is compiling host and device code in single source, keep using different data type for host and device will just create more problems in the long term.

So please limit use cases of ```half_float::half``` in your code, so it's will be easier for us to remove it later.

**Comment by qianfengz** [comment]
> @qianfengz Please don't use `std:: numeric_limits` in host or device code, use `ck::NumericLimits<ck::half_t>` on host as well.
> 

I can replace std::numeric_limits by ck::NumericLimits<>  very soon.  

> At some point, we would add all math function for `ck::half_t` for host too, and remove dependency on `half_float::half` even on host. Because unlike MIOpen, CK is compiling host and device code in single source, keep using different data type for host and device will just create more problems in the long term.
> 
> So please limit use cases of `half_float::half` in your code, so it's will be easier for us to remove it later.

Replace half_float::half by ck::half_t  really need the isnan(ck::half_t) and abs(ck::half_t) are completely implemented for host side

**Comment by qianfengz** [comment]
Have been solved by P.R 195 and merged into develop
