### ISSUE TITLE
Reduction modules overhaul

### ISSUE THREAD

**Issue by asroy** [ROCmSoftwarePlatform/composable_kernel#218]
# Design Document
https://ontrack-internal.amd.com/browse/LWPCK-205

# Misc
- [ ] ```ThreadwiseReduction``` support pointwise operations https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/213#discussion_r861964812

**Comment by qianfengz** [comment]
### Merging reduction kernels


1) Old reduction kernels

 

>  `kern_reduce_threadwise,  kern_reduce_blockwise,  kern_reduce_blockwise_second_call, kern_reduce_multiblock_atomic_add, kern_reduce_multiblock_partial_reduce`

2) New reduction kernels

> `kern_reduce_threadwise, kern_reduce_blockwise`

3) The `kern_reduce_threadwise`

> 
> * Be Kept the same as the old `kern_reduce_threadwise`
> * Does not use LDS
> * Support similar tunable as other reduction kernels

4) The `kern_reduce_blockwise`

> 
> * Implement functions provided by the old `kern_reduce_blockwise, kern_reduce_blockwise_second_call, kern_reduce_multiblock_atomic_add, kern_reduce_multiblock_partial_reduce`
> * Use LDS for work-group local reduction
> * Each thread has `blkGroupId` and local `blockId`
> * Most codes from old four kernels can be shared in the new kernel
> * Use template bool parameter `HaveInputIndex` of true to indicate `blockwise`_second-call, where indices could be read from input
> * Use template bool parameter `IsMultiBlockPartialReduce of true` to indicate `MltiblockPartialReduce`, which has different final reduction method as others 
> * Use runtime parameter `blkGroupSize` to choose between `multiblock_atomic_add` and `blockwise` for final reduction
> * Naming the Output tensor descriptor flexibly to support multiple cases (2d for `MultiBlockPartialReduce`, 1d for others)



### Merging DeviceReduce Interfaces


1) Old DeviceReduce Interfaces

> `DeviceReduceThreadwise, DeviceReduceBlockwise, DeviceReduceBlockwiseSecondCall, DeviceReduceMultiblockAtomicAdd, DeviceReduceMultiblockPartialReduce`         


2) New DeviceReduce Interfaces

> `DeviceReduceCompleteOrFinalReduce,  DeviceReducePartialReduce`  

3) The `DeviceReduceCompleteOrFinalReduce`

> * To replace the old `DeviceReduceThreadwise, DeviceReduceBlockwise, DeviceReduceBlockwiseSecondCall, DeviceReduceMultiblockAtomicAdd`
> * The tunable are kept same as the old interfaces
> * Use existing template parameter `BlockSize == MThreadClusterSize` to indicates the situation provided by old `DeviceReduceThreadwise`, `kern_reduce_threadwise` is called in this case
> * Use template bool parameter `UseMultiBlock of true` to indicate the use of multi-block method, which will fix down the value of `blkGroupSize` bigger than 1 at run-time; and for `UseMultiBlock of false`, `blkGroupSize` of 1 is used to call the `kern_reduce_blockwise`. For `Multiblock` method, either AtomicAdd or other Atomic operations are used in the kernel to finalize the reduction (eg. AtomixMin)
> * Use template `HaveInputIndex of true` to indicate the old `DeviceReduceBlockwiseSecondCall` method, which will tell the kernel to read indices from input
> * `UseMultiBlock` of true is restricted, the following should be considered when using it
> -- MIN, MAX, could not be used with AtomicAdd, could be used with AtomicMin
> -- NORM2 could not be used with AtomicAdd 
> -- AtomicAdd can only be used with `Add, AVG, NORM1`
> -- `OutDataType` of `int8, half_t, bhalf_t` could not be used with AtomicAdd
> -- `Beta != 0.0f` could not go with `UseMultiBlock of true`
> -- Most `AccElementwiseOp` could not go with `UseMultiBlock of true` (eg. `sqrt`)       

4) The `DeviceReducePartialReduce` 

> 
> * To replace the old `DeviceReduceMultiblockPartialReduce`
> * The shape of the output tensor must be 2D, to represent the shape of the workspace buffer used by the old `DeviceReduceMultiblockPartialReduce`
> * The dim-0 length of the output tensor must be same as the invariant length of the input tensor, the dim-1 length of the output tensor must be bigger than 1, indicating the number of work-groups working on single `toReduce` length       
> * It is up to the user to allocate the output tensor space (which is actually a workspace in perspective of complete reduction) 
> * Helper functions will be provided for the user to determine a suitable value of the number of work-groups working on single `toReduce` length



### Implementation Steps


1) Merge the Reduction Kernels, which is easier
2) Refine the DeviceReduce base API
3) Replace DeviceReduceXXXX by `DeviceReduceCompleteOrFinalReduce and DeviceReducePartialReduce`
4) Merge the DeviceReduce Instances 
5) Change to the applications (examples, profiler and ctest of `Reduction, Bnorm-fwd and Pooling`) 
5) Remove `Rank` and `NumReduceDims` from tempalte parameters (optional)
