### ISSUE TITLE
Index transformation with wave-dependent extents generates too many branch instructions

### ISSUE THREAD

**Issue by rosenrodt** [ROCmSoftwarePlatform/composable_kernel#252]
The issue is first found on hipclang build 9110.

In PR #239, we found that compiler generates many branch instructions in ISA disassembly when index transformation's input extent is a wave- & runtime-dependent value.

```
M01_adapt = (block_1d_id < N0 * M00 * M01) ? M01 : M0 % M01;

const auto m00_n0_m01adapt_to_m0_n0_block_cluster_adaptor =
    make_single_stage_tensor_adaptor(
        make_tuple(make_insert_transform(1),
                    make_unmerge_transform(make_tuple(M00, M01_adapt)), // <-- M01_adapt is wave- & runtime-dependent
                    make_pass_through_transform(make_tuple(N0))),
        make_tuple(Sequence<>{}, Sequence<0>{}, Sequence<1>{}),
        make_tuple(Sequence<0>{}, Sequence<1, 3>{}, Sequence<2>{}));
```

To work around this problem, an equivalent transformation in plain code is used instead. The goal here is to avoid using plain code and to use index transformation where possible. To that end, we need to understand why the resulting ISA has so many branch codes in the first place.

**Comment by asroy** [comment]
The branching is because the transform is constructed on GPU

**Comment by rosenrodt** [comment]
> The branching is because the transform is constructed on GPU

That does not quite explain everything. A counterexample is C shuffle block descriptor being constructed on GPU which works out just fine. There are plenty more similar cases.

https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/40b59a63cc6308c01390e6ab07015a2f34a7b16a/include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdl_cshuffle_v1.hpp#L480-L497

**Comment by asroy** [comment]
> > The branching is because the transform is constructed on GPU
> 
> That does not quite explain everything. A counterexample is C shuffle block descriptor being constructed on GPU which works out just fine. There are plenty more similar cases.
> 
> https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/40b59a63cc6308c01390e6ab07015a2f34a7b16a/include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdl_cshuffle_v1.hpp#L480-L497

since this transformation is ```constexpr``` and is evaluated at compile time, there will be no instruction in run time.

But if he transform need to be evaluated at run time, compiler doesn't generate every clean isa, and there will be branching and scratch mem. It could be because compiler doesn't deal with C++ constructor very well.

This is an compiler issue that a compiler improvement would be desired.

**Comment by rosenrodt** [comment]
Thanks for explanation. Closing this issue as workaround using plain code is already in place.
