### ISSUE TITLE
Standardize the element-wise operations and Reduction Accumulator operations

### ISSUE THREAD

**Issue by qianfengz** [ROCmSoftwarePlatform/composable_kernel#267]
From the discussion with Chao,  some specifications for the element-wise operations and Reduction Accumulator operations should be emphasized,  P.R will be made to make the codes consistent with the specifications. 

### For Element-wise Operations

1. The definitions of binary element-wise operations  should be put in file  `binary_element_wise_operation.hpp` with namespace `ck::tensor_operation::element_wise`
2. The definitions of unary element-wise operations should be put in file `unary_element_wise_operation.hpp` with namespace `ck::tensor_operation::element_wise`
3. The definitions of ternary or higher-ary element-wise operations should be put in file `element_wise_operation.hpp`  with namespace `ck::tensor_operation::element_wise` at present
4. File `binary_element_wise_operation.hpp`  and `unary_element_wise_operation.hpp` will be included by file `element_wise_operation.hpp` for compatibility with current codes in short time 
5. Each element-wise operation should not have data type as class template parameter, rather it should have the data type as the template parameter of `operator()`
6. Each binary element-wise operation should have the following operator() format
>    ```C++
>   template <typename T>
>  __host__ __device__ constexpr void operator()(T& y, const T& x0, const T& x1) const 
> {
>     ...  
> }
> ```
7. Each unary element-wise operation should have the following operator() format
> ```C++
> template <typename T>
>__host__ __device__ constexpr void operator()(T& y, const T& x) const 
> {
>   ...
> }
> ```
8.  Each element-wise operation either has or not have a specific constructor
9.  The `InElementwiseOperation` and `AccElementwiseOperation` used by Reduction are implemented as generic unary element-wise operations with or without a specific constructor

### For Reduction Accumulator Operations

1.  The definitions of the reduction accumulator operations should be put in separate file as element-wise operations, currently the file is `utility/reducton_operator.hpp`
2. Each reduction accumulator operation should not have data type as class template parameter, rather it should have the data type as the template parameter of `operator()`
3. Each reduction accumulator operation should have the following operator() format
> ```C++
> template <typename T>
> __host__ __device__ constexpr void operator()(T& a,  const T& b) const
> {
>    ... 
> }
> ...
4. Each reduction accumulator operation should define a static interface `GetIdentityValue()` , which should have a data type as template parameter, like 
> ```C++
> template <typename T>
> __host__ __device__ static constexpr T GetIdentityValue() 
> {
>   ... 
> }
> ```
> 
5. Each reduction accumulator operation should define a static interface `IsCompatibleInMemoryDataOperation()`, which should have a data type template paramete, like 
> ```C++
> template <typename T>
>  __host__ __device__ static constexpr bool IsCompatibleInMemoryDataOperation(InMemoryDataOperationEnum operation)
> {
>   ...
> }
>

**Comment by qianfengz** [comment]
Please give comments.   P.R will be submitted to fix the inconsistency in current codes

**Comment by qianfengz** [comment]
For implementing a template member function or operator in a non-template class,  we have the following two methods:

### Method 1
```C++
#include <limits>
#include <iostream>
#include <cmath>

namespace Test {

struct InverseVariance
{
    template <typename T>
    T operator()(T x);
};

template <>
float InverseVariance::operator()<float>(float x)
{
     return( 1.0f / std::sqrt(std::numeric_limits<float>::epsilon() + x * x) );
};

template <>
double InverseVariance::operator()<double>(double x)
{
     return( 1.0f / std::sqrt(std::numeric_limits<double>::epsilon() + x * x) );
};

}; // namespace Test

int main(int argc, char *argv[])
{
    using namespace Test;

    double f64_var = ::atof(argv[1]);
    float f32_var = static_cast<float>(f64_var);

    InverseVariance inv_variance;

    std::cout << "Inverse varaince for double type: " << inv_variance(f64_var)  << std::endl;
    std::cout << "Inverse varaince for float type: " << inv_variance(f32_var)  << std::endl;
};
```

### Method 2
```C++
#include <limits>
#include <iostream>
#include <cmath>

namespace Test {

struct InverseVariance
{
    template <typename T>
    T operator()(T x);
};

template <>
float InverseVariance::operator()<float>(float x)
{
     return( 1.0f / std::sqrt(std::numeric_limits<float>::epsilon() + x * x) );
};

template <>
double InverseVariance::operator()<double>(double x)
{
     return( 1.0f / std::sqrt(std::numeric_limits<double>::epsilon() + x * x) );
};

}; // namespace Test

int main(int argc, char *argv[])
{
    using namespace Test;

    double f64_var = ::atof(argv[1]);
    float f32_var = static_cast<float>(f64_var);

    InverseVariance inv_variance;

    std::cout << "Inverse varaince for double type: " << inv_variance(f64_var)  << std::endl;
    std::cout << "Inverse varaince for float type: " << inv_variance(f32_var)  << std::endl;
};
```

**Which one is preferred ?**

**Comment by qianfengz** [comment]
Personally,  I prefer to use Method 1,  since it makes the codes more compact.

**Comment by rosenrodt** [comment]
What's the main difference between those two? You mean `float impl_operator(float x)` instead of `template <> float operator()<float>(float x)`? Or putting function definitions inside the struct scope?

**Comment by qianfengz** [comment]
> What's the main difference between those two? You mean `float impl_operator(float x)` instead of `template <> float operator()<float>(float x)`? Or putting function definitions inside the struct scope?

I have tested that,  put `template <> float operator()<float>(float x)` inside the struct scope will lead to compiler error on Linux.  So this is the reason that we can only have the above two choices

**Comment by rosenrodt** [comment]
I tried defining `operator()` inside struct scope. It works just fine. GCN ISA looks legit too.
```c++
struct SquaredInverse
{
    template <typename T>
    T operator()(T x);

    template <>
    float operator()<float>(float x)
    {
         return( 1.0f / (x * x) );
    };
};

int main(int argc, char** argv)
{
    SquaredInverse inv;
    float in = *reinterpret_cast<float*>(&argv[2]);
    float out = inv(in);
    return int(out);
}
```

Online compiler https://gcc.godbolt.org/z/Goq5WEd6j

**Comment by qianfengz** [comment]
Yes.   I found this (in-scope operator instantiation) works with clang++ with any of c++11/c++14/c++17,  but fails with g++ with any of c+11/c++14/c++17

**Comment by qianfengz** [comment]
I will use struct-scope template overloading since it works with clang++.   Thanks.
