### ISSUE TITLE
DeviceMemory::GetBufferSize and DeviceMemory::GetDeviceBuffer should be const, but aren't

### ISSUE THREAD

**Issue by swolchok** [ROCmSoftwarePlatform/composable_kernel#350]
See here: https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/develop/library/include/ck/library/utility/device_memory.hpp#L22

**Comment by asroy** [comment]
@swolchok Thanks for pointing out! Will fix it soon

**Comment by asroy** [comment]
Fixed in PR #https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/338
