### ISSUE TITLE
random failure of example_gemm_max_xdl_fp16 on gfx908 (but pass on gfx90a)

### ISSUE THREAD

**Issue by asroy** [ROCmSoftwarePlatform/composable_kernel#358]
on gfx908, random failure:
<img width="910" alt="image" src="https://user-images.githubusercontent.com/22615726/184503929-518c5a0b-16e8-4810-b14e-257503f21b54.png">

on gfx908, sometimes pass:
<img width="910" alt="image" src="https://user-images.githubusercontent.com/22615726/184503958-ce7f7a54-9875-49eb-9d6e-7b8884eaab8c.png">

```example_gemm_max_xdl_fp16``` is currently disabled from CI test because of this bug

**Comment by asroy** [comment]
fixed by PR #360

**Comment by aosewski** [comment]
The same issue observed with int8 data type. And implicitly with int4. Tested only on gfx908.

![gemm_max_xdl_int8](https://user-images.githubusercontent.com/19374865/185641747-c2010c07-da17-4ed1-9d9e-d65eb009f5fd.png)

**Comment by rocking5566** [comment]
> The same issue observed with int8 data type. And implicitly with int4. Tested only on gfx908.
> 
> ![gemm_max_xdl_int8](https://user-images.githubusercontent.com/19374865/185641747-c2010c07-da17-4ed1-9d9e-d65eb009f5fd.png)

I found the root cause in int8 is
1. data type error
2. rounding 
Detail of the modification is as follow commit 
https://github.com/ROCmSoftwarePlatform/composable_kernel/commit/1fc39f634f5c0bdde2275ed9c13e1f0e8e8feeaa

**Comment by rocking5566** [comment]
I send the PR https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/371 for this issue
