### ISSUE TITLE
Gemm reduction wrong results with int8 and UnaryDivide

### ISSUE THREAD

**Issue by aosewski** [ROCmSoftwarePlatform/composable_kernel#390]
The #368 has added `example_gemm_mean_meansquare_xdl_int8` which produces incorrect results:
![gemm_meansquare_int8_err](https://user-images.githubusercontent.com/19374865/187163865-98aa0fe5-5e7f-41c4-94ea-fa52c9045f05.png)
The above results are done when A and B tensors where initialized with value `1`.
The example data type & reduce ops configuration:
```c++
// DataType
using ADataType         = INT8;
using BDataType         = INT8;
using GemmAccDataType   = INT32;
using CShuffleDataType  = INT32;
using DsDataType        = ck::Tuple<>;
using EDataType         = INT8;
using ReduceAccDataType = INT32;
using R0DataType        = INT32;
using R1DataType        = INT32;
using RsDataType        = ck::Tuple<R0DataType, R1DataType>;

// Layout
using ALayout = Row;
using BLayout = Col;
using ELayout = Row;

// Elementwise op
using Square       = ck::tensor_operation::element_wise::UnarySquare;
using Div          = ck::tensor_operation::element_wise::UnaryDivide;
using AElementOp   = PassThrough;
using BElementOp   = PassThrough;
using CDEElementOp = PassThrough;
using QsElementOp  = ck::Tuple<PassThrough, Square>;
using RsElementOp  = ck::Tuple<Div, Div>;

// ReduceOp
using R0ThreadReduceOp = ck::reduce::Add;
using R1ThreadReduceOp = ck::reduce::Add;
using RsThreadReduceOp = ck::Tuple<R0ThreadReduceOp, R1ThreadReduceOp>;

static constexpr auto R0GlobalReduceOp = ck::InMemoryDataOperationEnum::AtomicAdd;
static constexpr auto R1GlobalReduceOp = ck::InMemoryDataOperationEnum::AtomicAdd;
using RsGlobalReduceOp = ck::InMemoryDataOperationEnumSequence<R0GlobalReduceOp, R1GlobalReduceOp>;
```
This looks to me like, there's no (or incorrect) casting when reading data from GEMM result `E` tensor to `EDataType`, since as long as the accumulated values are in `int8` data type range the results are OK.

**Comment by aosewski** [comment]
@rocking5566

**Comment by rocking5566** [comment]
> This looks to me like, there's no (or incorrect) casting when reading data from GEMM result E tensor to EDataType
EDataType mean the output type of E tensor. It does not mean we reduce data from E datatype.
kerenl reduce data from ReduceAccDataType 

https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/88e43744d829858deedbbeb036a89759d536b79c/include/ck/tensor_operation/gpu/grid/gridwise_gemm_multiple_d_multiple_r_xdl_cshuffle.hpp#L704-L705

We cast E into EDataType in global write
https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/88e43744d829858deedbbeb036a89759d536b79c/include/ck/tensor_operation/gpu/grid/gridwise_gemm_multiple_d_multiple_r_xdl_cshuffle.hpp#L871-L876
Note that type of e_thread_buf is ReduceAccDataType, type of e_grid_buf is EDataType

**Comment by aosewski** [comment]
OK, but as you can see the E results are OK - there's no message about any error. What I'm thinking about is what type is used when E results are passed to reduction part? Does results from registers of `ReduceAccDataType` datat type are reused without prior casting to `EDataType`? This looks to mi like such situation.

https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/88e43744d829858deedbbeb036a89759d536b79c/include/ck/tensor_operation/gpu/grid/gridwise_gemm_multiple_d_multiple_r_xdl_cshuffle.hpp#L740-L741

Here you're reading `ReduceAccDataType` and save it directly in `RsDataType` which omits casting to `EDataType` of GEMM results if I understand it correctly?

**Comment by rocking5566** [comment]
As I know, we only cast into EDataType in global write
Type of E "value" is as follow
GemmAccDataType -> CShuffleDataType (c_thread_copy_vgpr_to_lds) -> ReduceAccDataType (c_reduce_thread_copy_lds_to_vgpr) -> EDataType (e_thread_copy_vgpr_to_global)

**Comment by aosewski** [comment]
The implementation is correct. The user have to setup proper data types through template parameters for both device operation and reference.
