### ISSUE TITLE
Not expose Acc0ElementOp compute detail to device level -- Originated by Anthony.

### ISSUE THREAD

**Issue by shaojiewang** [ROCmSoftwarePlatform/composable_kernel#391]
We should never require user to specify `Acc0ElementOp = ResetNaNToMinusInfinity` because users are not concerned with how we handle padding with NaNs and INFs. What I mean is to keep `Acc0ElementOp = scale` as it is, and leave ResetNaNToMinusInfinity details to gridwise level. To reiterate: we can and should do ResetNaNToMinusInfinity somewhere somehow once N padding is on.

And once we've done that, the difference between the two example code should be pretty minimal. We may consider reorg the code into what @poyenc did with https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/develop/example/01_gemm/run_gemm_example.inc

_Originally posted by @rosenrodt in https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/385#discussion_r956874214_

**Comment by rosenrodt** [comment]
Tentative fix in https://github.com/rosenrodt/composable_kernel/commit/72d4c98e40f440e29327cc8431126e97b45fec10
