### ISSUE TITLE
Test failures for instances using LoopScheduler::Interwave

### ISSUE THREAD

**Issue by geyyer** [ROCmSoftwarePlatform/composable_kernel#392]
The PR adds more instances using LoopScheduler::Interwave and pipeline v2: https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/381. Some of the test cases for instances using LoopScheduler::Interwave fail with something like:

Warm up 1 time
Start running 10 times...                                                                                                             
Perf: 0.015504 ms, 6.492731 TFlops, 88.7678 GB/s, DeviceBatchedGemmXdl<256, 128, 64, 4> NumGemmKPrefetchStage: 1, LoopScheduler: Interwave, PipelineVersion: 1                                                                                                              
Error: Incorrect results!        out[4194400] != ref[4194400]: 59 != -38
Error: Incorrect results!        out[4194401] != ref[4194401]: 63 != 97                                                               
Error: Incorrect results!        out[4194402] != ref[4194402]: -32 != -91
Error: Incorrect results!        out[4194403] != ref[4194403]: 44 != 8                                                                   
max err: 191

Repro commands:
./bin/test_gemm_fp16
./bin/test_batched_gemm_fp16

**Comment by rosenrodt** [comment]
Are these errors coming out from `DeviceBatchedGemmXdl` kernels but not `DeviceBatchedGemmXdlCShuffle`? It was found at the time of https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/184#issue-1200841646 that the non-C-Shuffle kernels could have issues related to the compiler:

> There is known verification [failures] in some DeviceGemmXdl kernels that have register spills. DeviceGemmXdlCShuffle kernels passed verifications.

**Comment by rosenrodt** [comment]
@geyyer I have pushed the fix https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/381/commits/cbf6893363e77eac63a64314be517629a7862648 to #381. The cause was misconfiguration. I've validated the result on MI250 locally and let's see what CI says.

**Comment by geyyer** [comment]
Thanks @rosenrodt , fixed by [37f0fc6](https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/381/commits/37f0fc647e61fa7341bb0818043a369b70405553)
