### ISSUE TITLE
arg print should be disabled

### ISSUE THREAD

**Issue by antinucleon** [ROCmSoftwarePlatform/composable_kernel#419]
https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/3fbe56f85cc55cd0e6bad58c95dad744ccaba5b5/include/ck/tensor_operation/gpu/device/device_grouped_conv_fwd_multiple_d_xdl_cshuffle.hpp#L1460

**Comment by asroy** [comment]
fix by https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/421
