### ISSUE TITLE
Invoke some instances will garbage fill my terminal

### ISSUE THREAD

**Issue by cloudhan** [ROCmSoftwarePlatform/composable_kernel#525]
Some `Invoker`s have suspicious `std::cout`. The must be removed or guarded by `ifdef`. Otherwise, your client will be garbage filled with nonsensical debug log.

For example:
https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/8784a72e23538d594ea6b1bd527478fba2962d30/include/ck/tensor_operation/gpu/device/impl/device_batched_gemm_xdl.hpp#L411-L424

https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/8ee36118be9b19b15c2471bffeeeb624afb14044/include/ck/tensor_operation/gpu/device/impl/device_conv2d_bwd_data_xdl_nhwc_kyxc_nhwk.hpp#L547-L583

**Comment by illsilin** [comment]
We've merged a fix to clean this up.

**Comment by cloudhan** [comment]
`DeviceBatchedGemmMultipleDGemmMultipleD_Xdl_CShuffle` is also affected. I think you should do a full repo cleanup, use some internal `define` to guard your dev debug code, instead of just `#if 0`, this will be easily forgotten after dev/debugging. You are handing hair scratching numerically code, I doubt the reviewer can notice these problems.

**Comment by illsilin** [comment]
Yes, I agree, using the #if 0/1 is a quick-and-dirty way that we should get rid of. In many instances we actually have a dedicated Print() function for that purpose. We may either use similar style in all instances, or come up with something better. For now I'm just going to clean up all the debug output cases that we come across as a short-term fix.
