### ISSUE TITLE
IsSupportedArgument is returning true for the below convolution-bias-activation configuration for 

### ISSUE THREAD

**Issue by bghimireamd** [ROCmSoftwarePlatform/composable_kernel#536]
When trying to integrate CK's [conv-bias-activation](https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/develop/include/ck/tensor_operation/gpu/device/device_conv_fwd_bias_activation.hpp) into MIOpen for the below problem configuration `IsSupportedArgument` is returning true. But in CK it eventually throws invalid setting error.  

Details: 

N = 64, K = 64, C = 3, input : 224,224, filter : 7,7, output : 112,112, strides : 2,2, dilation : 1,1, lpadding : 3,3, rpadding : 2,2

DeviceConv2dFwdXdl_C_Shuffle_Bias_Activation_Input_N_Hi_Wi_C_Weight_K_Y_X_C_Output_N_Ho_Wo_K<256, 256, 128, 4>
N 64, K 64, C 3,
Y X 7, 7,
Hi Wi 224, 224,
Ho Wo 112, 112,
Strides 2, 2,
Dilations 1, 1,
InLeftPads 3, 3,
InLeftPads 2, 2,
arg.a_grid_desc_k0_m_k1_{18, 802816, 8}
arg.b_grid_desc_k0_n_k1_{18, 64, 8}
arg.c_grid_desc_m_n_{ 802816, 64}
arg.c0_grid_desc_m_n_{ 802816, 64}
unknown file: Failure
**C++ exception with description "wrong! GridwiseGemm_km_kn_m0m1n0n1_xdlops_v3r2 has invalid setting"**

**Comment by illsilin** [comment]
We have recently realized that the tensor size checks inside and before IsSupportedArgument are often ignored or are incomplete. So the fact that IsSupportedArgument is returning "true", does not necessarily mean that the tensor size should be supported. I'm going to review the tensor dimension checks for all kernels in the next few weeks.

**Comment by illsilin** [comment]
Ran this example with the latest CK version on MI100 and did not observe any error messages.

This is my command line:
./bin/ckProfiler conv_fwd_bias_relu 1 1 1 1 1 2 0 1 64 64 3 7 7 224 224 2 2 1 1 3 3 2 2

I do not see the offending kernel <256, 256, 128, 4> on the list. These are the only ones I got:

launch_and_time_kernel: grid_dim {6272, 1, 1}, block_dim {128, 1, 1}
Warm up 1 time
Start running 10 times...
Perf: 0.98176 ms, 15.3864 TFlops, 124.314 GB/s, DeviceConv2dFwdXdl_C_Shuffle_Bias_Activation_Input_N_Hi_Wi_C_Weight_K_Y_X_C_Output_N_Ho_Wo_K<128, 128, 64, 4>
launch_and_time_kernel: grid_dim {12544, 1, 1}, block_dim {64, 1, 1}
Warm up 1 time
Start running 10 times...
Perf: 2.36368 ms, 6.3908 TFlops, 51.6344 GB/s, DeviceConv2dFwdXdl_C_Shuffle_Bias_Activation_Input_N_Hi_Wi_C_Weight_K_Y_X_C_Output_N_Ho_Wo_K<64, 64, 64, 4>
launch_and_time_kernel: grid_dim {6272, 1, 1}, block_dim {256, 1, 1}
Warm up 1 time
Start running 10 times...
Perf: 0.644476 ms, 23.4389 TFlops, 189.374 GB/s, DeviceConv2dFwdXdl_C_Shuffle_Bias_Activation_Input_N_Hi_Wi_C_Weight_K_Y_X_C_Output_N_Ho_Wo_K<256, 128, 64, 4>
launch_and_time_kernel: grid_dim {12544, 1, 1}, block_dim {128, 1, 1}
Warm up 1 time
Start running 10 times...
Perf: 1.10028 ms, 13.729 TFlops, 110.923 GB/s, DeviceConv2dFwdXdl_C_Shuffle_Bias_Activation_Input_N_Hi_Wi_C_Weight_K_Y_X_C_Output_N_Ho_Wo_K<128, 128, 32, 4>
launch_and_time_kernel: grid_dim {25088, 1, 1}, block_dim {64, 1, 1}
Warm up 1 time
Start running 10 times...
Perf: 1.34275 ms, 11.2499 TFlops, 90.8935 GB/s, DeviceConv2dFwdXdl_C_Shuffle_Bias_Activation_Input_N_Hi_Wi_C_Weight_K_Y_X_C_Output_N_Ho_Wo_K<64, 64, 32, 4>
launch_and_time_kernel: grid_dim {25088, 1, 1}, block_dim {64, 1, 1}
Warm up 1 time
Start running 10 times...
Perf: 0.962029 ms, 15.702 TFlops, 126.864 GB/s, DeviceConv2dFwdXdl_C_Shuffle_Bias_Activation_Input_N_Hi_Wi_C_Weight_K_Y_X_C_Output_N_Ho_Wo_K<64, 32, 64, 4>
launch_and_time_kernel: grid_dim {6272, 1, 1}, block_dim {256, 1, 1}
Warm up 1 time
Start running 10 times...
Perf: 0.543022 ms, 27.818 TFlops, 224.755 GB/s, DeviceConv2dFwdXdl_C_Shuffle_Bias_Activation_Input_N_Hi_Wi_C_Weight_K_Y_X_C_Output_N_Ho_Wo_K<256, 128, 64, 4>
C=3 Ablock=1 Bblock=1
launch_and_time_kernel: grid_dim {6272, 1, 1}, block_dim {256, 1, 1}
Warm up 1 time
Start running 10 times...
Perf: 0.406575 ms, 37.1538 TFlops, 300.183 GB/s, DeviceConv2dFwdXdl_C_Shuffle_Bias_Activation_Input_N_Hi_Wi_C_Weight_K_Y_X_C_Output_N_Ho_Wo_K<256, 128, 64, 2>
launch_and_time_kernel: grid_dim {3136, 1, 1}, block_dim {256, 1, 1}
Warm up 1 time
Start running 10 times...
Perf: 0.441311 ms, 34.2294 TFlops, 276.556 GB/s, DeviceConv2dFwdXdl_C_Shuffle_Bias_Activation_Input_N_Hi_Wi_C_Weight_K_Y_X_C_Output_N_Ho_Wo_K<256, 256, 64, 2>
launch_and_time_kernel: grid_dim {6272, 1, 1}, block_dim {128, 1, 1}
Warm up 1 time
Start running 10 times...
Perf: 0.377551 ms, 40.0099 TFlops, 323.26 GB/s, DeviceConv2dFwdXdl_C_Shuffle_Bias_Activation_Input_N_Hi_Wi_C_Weight_K_Y_X_C_Output_N_Ho_Wo_K<128, 128, 64, 2>
 Bblock=1
launch_and_time_kernel: grid_dim {12544, 1, 1}, block_dim {128, 1, 1}
Warm up 1 time
Start running 10 times...
Perf: 0.507999 ms, 29.7359 TFlops, 240.251 GB/s, DeviceConv2dFwdXdl_C_Shuffle_Bias_Activation_Input_N_Hi_Wi_C_Weight_K_Y_X_C_Output_N_Ho_Wo_K<128, 64, 64, 2>
Best Perf: 0.377551 ms, 40.0099 TFlops, 323.26 GB/s, DeviceConv2dFwdXdl_C_Shuffle_Bias_Activation_Input_N_Hi_Wi_C_Weight_K_Y_X_C_Output_N_Ho_Wo_K<128, 128, 64, 2>

**Comment by bghimireamd** [comment]
After further digging I was able find the issue. In MIOpen we call `add_device_conv2d_fwd_xdl_c_shuffle_bias_relu_nhwc_kyxc_nhwk_f16_instances`  to get list of all the CK kernels. Then use `IsSupportedArgument` to detect the correct kernel from the list. I was not using the correct kernel ID from the list, hence the ERROR. We can close this ticket.

**Comment by illsilin** [comment]
Good catch!
