### ISSUE TITLE
Numerical error for convolution-bias-activation CK kernel

### ISSUE THREAD

**Issue by bghimireamd** [ROCmSoftwarePlatform/composable_kernel#537]
When trying to integrate CK's [conv-bias-activation](https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/develop/include/ck/tensor_operation/gpu/device/device_conv_fwd_bias_activation.hpp) into MIOpen I am gettting a numerical error for below configuration. 

Details: 

N = 64, K = 2048, C = 1024, input : 14,14, filter : 1,1, output : 7,7, strides : 2,2, dilation : 1,1, lpadding : 0,0, rpadding : 0,0

DeviceConv2dFwdXdl_C_Shuffle_Bias_Activation_Input_N_Hi_Wi_C_Weight_K_Y_X_C_Output_N_Ho_Wo_K<256, 256, 128, 4>

N 64, K 2048, C 1024,
Y X 1, 1,
Hi Wi 14, 14,
Ho Wo 7, 7,
Strides 2, 2,
Dilations 1, 1,
InLeftPads 0, 0,
InLeftPads 0, 0,
arg.a_grid_desc_k0_m_k1_{128, 3328, 8}
arg.b_grid_desc_k0_n_k1_{128, 2048, 8}
arg.c_grid_desc_m_n_{ 3328, 2048}
arg.c0_grid_desc_m_n_{ 3328, 2048}

MIOpen(HIP): Warning [ref_conv_fwd] GPU reference skipped
/root/debug_miopen/test/gtest/cba.hpp:206: Failure
Value of: error < threshold
  Actual: false
Expected: true
Error beyond tolerance Error:0.16093283598174132,  Threshold: 0.078125

**Comment by illsilin** [comment]
I'm going to look into this.

**Comment by illsilin** [comment]
I just re-ran this example with ckProfiler using the latest version of CK and did not observe any errors.

This is the command I used (verification is ON):
root@rocm-framework-11:/composable_kernel/build# ./bin/ckProfiler conv_fwd_bias_relu 1 1 1 1 1 2 0 1 64 2048 1024 1 1 14 14 2 2 1 1 0 0 0 0

Tensor parameters:
in_n_c_hi_wi: dim 4, lengths {64, 1024, 14, 14}, strides {200704, 1, 14336, 1024}
wei_k_c_y_x: dim 4, lengths {2048, 1024, 1, 1}, strides {1024, 1, 1024, 1024}
out_n_k_ho_wo: dim 4, lengths {64, 2048, 7, 7}, strides {100352, 1, 14336, 2048}
bias_k: dim 1, lengths {2048}, strides {1}

The offending kernel Perf: 0.983088 ms, 13.3796 TFlops, 43.4687 GB/s, DeviceConv2dFwdXdl_C_Shuffle_Bias_Activation_Input_N_Hi_Wi_C_Weight_K_Y_X_C_Output_N_Ho_Wo_K<256, 256, 128, 4> does appear on the list, but no error message.

There's a couple of things I need to clarify:
which version (commit) of CK did you use?
which GPU architecture did you run on? (I ran on MI100).

**Comment by bghimireamd** [comment]
CK commit : eef009d001b928db1bb377a105c93b75e0dccc7b
GPU architecture : MI100

**Comment by illsilin** [comment]
Hmm, I re-built and re-ran that test with the commit you are using and still don't observe any error messages. The offending kernel is there: 
launch_and_time_kernel: grid_dim {208, 1, 1}, block_dim {256, 1, 1}
Warm up 1 time
Start running 10 times...
Perf: 0.98305 ms, 13.3801 TFlops, 43.4704 GB/s, DeviceConv2dFwdXdl_C_Shuffle_Bias_Activation_Input_N_Hi_Wi_C_Weight_K_Y_X_C_Output_N_Ho_Wo_K<256, 256, 128, 4>

Could this be related to the previous ticket, #536? We are talking about the same kernel here, right?

**Comment by bghimireamd** [comment]
I am not sure if this issue is related to #536 because even after fixing the Kernel id. I still see the same numerical error. Currently I am trying to see if the buffer prior to sending them to CK is good.

**Comment by bghimireamd** [comment]
So, in [profile_conv_fwd_bias_relu_impl.hpp](https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/develop/profiler/include/profiler/profile_conv_fwd_bias_relu_impl.hpp#L112) when I changed the rage from (-3.0,3.0). I was able to recreate the issue in CK as well. 

Basically below is the code modification I made : 
`
         in_n_c_hi_wi.GenerateTensorValue(GeneratorTensor_3<InDataType>{-3.0, 3.0});
        wei_k_c_y_x.GenerateTensorValue(GeneratorTensor_3<WeiDataType>{-3.0, 3.0});
        bias_k.GenerateTensorValue(GeneratorTensor_3<OutDataType>{-3.0, 3.0});
`

**Comment by illsilin** [comment]
OK, I think I understand what's happening.
In all likelihood, we are looking at a round-off error.
All the differences start to creep into 3rd or 4th significant digit for large indices as you expand the dynamic range of the input values.
For the inputs dynamic range {-3.0 , 3.0} I got:
Error: Incorrect results!        out[523840] != ref[523840]: 2.71875 != 2.722656
Error: Incorrect results!        out[788401] != ref[788401]: 2.71875 != 2.722656
Error: Incorrect results!        out[1609389] != ref[1609389]: 2.296875 != 2.292969
Error: Incorrect results!        out[2322556] != ref[2322556]: 5.757812 != 5.765625
For the range {-2.0, 2.0}:
Error: Incorrect results!        out[627939] != ref[627939]: 6.671875 != 6.664062
Error: Incorrect results!        out[2002953] != ref[2002953]: 2.707031 != 2.703125
Error: Incorrect results!        out[2205902] != ref[2205902]: 2.855469 != 2.851562
Error: Incorrect results!        out[3320893] != ref[3320893]: 2.265625 != 2.261719
And for the range {-1.0, 1.0} the error goes away.
The default value ranges are:
        in_n_c_hi_wi.GenerateTensorValue(GeneratorTensor_3<InDataType>{0.0, 1.0});
        wei_k_c_y_x.GenerateTensorValue(GeneratorTensor_3<WeiDataType>{-0.5, 0.5});
        bias_k.GenerateTensorValue(GeneratorTensor_3<OutDataType>{0.0, 1.0});

If we want to handle cases of this size with larger dynamic ranges, we may need to change the type of the variables that accumulate the results.

**Comment by bghimireamd** [comment]
You mean change type of [AccDataType ](https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/develop/include/ck/tensor_operation/gpu/device/impl/device_conv2d_fwd_xdl_c_shuffle_bias_activation_nhwc_kyxc_nhwk.hpp#L30)tensor? It seems like this type is hardcoded by [add_device_conv2d_fwd_xdl_c_shuffle_bias_relu_nhwc_kyxc_nhwk_f16_instances](https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/develop/library/src/tensor_operation_instance/gpu/conv2d_fwd_bias_relu/device_conv2d_fwd_xdl_c_shuffle_bias_relu_nhwc_kyxc_nhwk_f16_instance.cpp#L137) function. 


⁠[conv-bias-activation fusion kernel](https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/develop/library/src/tensor_operation_instance/gpu/conv2d_fwd_bias_relu/device_conv2d_fwd_xdl_c_shuffle_bias_relu_nhwc_kyxc_nhwk_f16_instance.cpp) only supports F16 for InData, WeiData, OutData and F32 for AccData.

**Comment by bghimireamd** [comment]
Big convolution requires small range (-1.0 , 1.0) of inputs, weights and bias for this kernel.

We can close this ticket now since it seems to be a round off error.

**Comment by illsilin** [comment]
One more proof that we are dealing with the round-off error: 
a test with large dynamic range {-5, 5} but using integer numbers does not throw an error and the output tensor is actually not zeros.
