### ISSUE TITLE
Bias support for DeviceBatchedGemmSoftmaxGemmPermute_Xdl_CShuffle

### ISSUE THREAD

**Issue by cloudhan** [ROCmSoftwarePlatform/composable_kernel#544]
DeviceBatchedGemmSoftmaxGemmPermute_Xdl_CShuffle currently do not support `bias addition`. Bias is needed for attention mask when apply this Operator for BERT with attention mask.

**Comment by ltqin** [comment]
https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/576

**Comment by zjing14** [comment]
@cloudhan The PR is merged.
