### ISSUE TITLE
Bug when reading data that is invalid from dynamic buffer, 

### ISSUE THREAD

**Issue by asroy** [ROCmSoftwarePlatform/composable_kernel#57]
https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/567f5e9c5f0aa6481570fba9267224626014542f/composable_kernel/include/utility/dynamic_buffer.hpp#L84-L95

load instructions will be issued no matter what, even if the element is invalid. Potential for OOB.
Fix:
 for LDS, it's fine, since LDS will wrap around OOB address
 for global, it means segmentation fault.

**Comment by j4yan** [comment]
Should be fixed in https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/60

**Comment by j4yan** [comment]
Update: If using if-statement to avoid invalid loading, the performance of conv3d will drop by 10%.

**Comment by asroy** [comment]
@j4yan Please check the code of dynamic_buffer and letting me know if the issue still exist

**Comment by j4yan** [comment]
@asroy I believe the issue is gone.

**Comment by asroy** [comment]
fixed
