### ISSUE TITLE
Debug build crash due to c assert

### ISSUE THREAD

**Issue by cloudhan** [ROCmSoftwarePlatform/composable_kernel#622]
A dev at MSFT met the following crash:
onnxruntime/build/Linux/Debug/_deps/composable_kernel-src/include/ck/tensor_operation/gpu/device/impl/device_gemm_xdl.hpp:80: static auto ck::tensor_operation::device::DeviceGemmXdl<_Float16, _Float16, _Float16, float, ck::tensor_layout::gemm::RowMajor, ck::tensor_layout::gemm::RowMajor, ck::tensor_layout::gemm::RowMajor, ck::tensor_operation::element_wise::PassThrough, ck::tensor_operation::element_wise::PassThrough, ck::tensor_operation::element_wise::PassThrough, ck::tensor_operation::device::GemmSpecialization::Default, 256, 256, 128, 4, 8, 32, 32, 4, 2, ck::Sequence<4, 64, 1>, ck::Sequence<1, 0, 2>, ck::Sequence<1, 0, 2>, 2, 8, 8, true, ck::Sequence<4, 64, 1>, ck::Sequence<0, 2, 1>, ck::Sequence<0, 2, 1>, 1, 2, 8, true, 7, 1, 1, ck::LoopScheduler::Default, ck::PipelineVersion::v1>::MakeAGridDescriptor_K0_M_K1(ck::index_t, ck::index_t, ck::index_t) [ADataType = _Float16, BDataType = _Float16, CDataType = _Float16, AccDataType = float, ALayout = ck::tensor_layout::gemm::RowMajor, BLayout = ck::tensor_layout::gemm::RowMajor, CLayout = ck::tensor_layout::gemm::RowMajor, AElementwiseOperation = ck::tensor_operation::element_wise::PassThrough, BElementwiseOperation = ck::tensor_operation::element_wise::PassThrough, CElementwiseOperation = ck::tensor_operation::element_wise::PassThrough, GemmSpec = ck::tensor_operation::device::GemmSpecialization::Default, BlockSize = 256, MPerBlock = 256, NPerBlock = 128, K0PerBlock = 4, K1 = 8, MPerXDL = 32, NPerXDL = 32, MXdlPerWave = 4, NXdlPerWave = 2, ABlockTransferThreadClusterLengths_K0_M_K1 = ck::Sequence<4, 64, 1>, ABlockTransferThreadClusterArrangeOrder = ck::Sequence<1, 0, 2>, ABlockTransferSrcAccessOrder = ck::Sequence<1, 0, 2>, ABlockTransferSrcVectorDim = 2, ABlockTransferSrcScalarPerVector = 8, ABlockTransferDstScalarPerVector_K1 = 8, ABlockLdsAddExtraM = true, BBlockTransferThreadClusterLengths_K0_N_K1 = ck::Sequence<4, 64, 1>, BBlockTransferThreadClusterArrangeOrder = ck::Sequence<0, 2, 1>, BBlockTransferSrcAccessOrder = ck::Sequence<0, 2, 1>, BBlockTransferSrcVectorDim = 1, BBlockTransferSrcScalarPerVector = 2, BBlockTransferDstScalarPerVector_K1 = 8, BBlockLdsAddExtraN = true, CThreadTransferSrcDstVectorDim = 7, CThreadTransferDstScalarPerVector = 1, NumPrefetch = 1, LoopSched = ck::LoopScheduler::Default, PipelineVer = ck::PipelineVersion::v1]: Assertion `K % K1 == 0' failed.
Aborted (core dumped)

It should be caused by as the c assert is only functional in debug build, or precisely, when NDEBUG is not defined https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/9096b1c7b2642000440b4b6d1a6a331378a75da1/include/ck/tensor_operation/gpu/device/impl/device_gemm_xdl.hpp#L80

Can ck dev clean all these things and ensure all unsupported shapes are correctly rejected by the `IsSupported` to avoid assertion failure?

**Comment by geyyer** [comment]
Hi @cloudhan, here is a PR removing these debug asserts https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/629.

**Comment by zjing14** [comment]
@cloudhan Please check if the fix resolves your problem.
