### ISSUE TITLE
[cppcheck][warning][ODR] possible UB on multiple `struct get_ref_desc_types` in ck namespace

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/composable_kernel#70]
**[Keywords]:**
cppcheck; warning;
**[Urgency: Low; Importance: Medium]**

**[Env]:**
cppcheck@2.6

**[Description]:**
A search on `struct get_ref_desc_types` will result 13 files with the same-named struct in the same namespace "ck". It violates ODR and may potentially result in UB.
https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/6260ced2f3a4d9a2a832563905135c01ba72b56b/composable_kernel/src/kernel_wrapper/gridwise_generic_reduction_first_call_blockwise_reduce_all_dims.cpp#L161
_(other files omitted, just search in the same folder)_

[Recommendation]:
1. A temporal method is `anonymous namespace`, just wrap around this struct and it should be local to its own translation unit (.cpp file and all its includes) ;
2. A deeper search seems to reveal that there are lots of duplications among these 13 files. Take this struct for example, it seems that only first call and second call, and all-dim and partial-dim have differences. Can we move the struct definition to a separate file and consolidate them?

**Comment by qianfengz** [comment]
Latest CK will not get the descriptor types from the kernels since they are passed from the host.

**Comment by qianfengz** [comment]
Change from dynamic kernels to templated "C.K" will be huge!   You can check my branch  "ck_new_reduce".

**Comment by asroy** [comment]
> Change from dynamic kernels to templated "C.K" will be huge! You can check my branch "ck_new_reduce".

Is this still an issue? Has it been fixed?

**Comment by qianfengz** [comment]
The issue does not exist in C.K
