### ISSUE TITLE
unexpected behavior in make_freeze_transform

### ISSUE THREAD

**Issue by j4yan** [ROCmSoftwarePlatform/composable_kernel#74]
In this function, the number of tuples for  upper indices is allowed to be different than the number of tuples for lower indices. 
See here https://github.com/j4yan/composable_kernel/blob/conv3d_splitN_rebased/composable_kernel/include/tensor_operation/gridwise_batched_gemm_xdlops_v2r3.hpp#L333

**Comment by asroy** [comment]
It's a bug, and ```transform_tensor_descriptor``` should do sanity check.

@j4yan Could you add such check?

**Comment by asroy** [comment]
fixed by PR #89
