### ISSUE TITLE
conv2d_fwd_xdl_bias_relu_atomic_add incorrect results.

### ISSUE THREAD

**Issue by j4yan** [ROCmSoftwarePlatform/composable_kernel#95]
conv2d_fwd_xdl_bias_relu_atomic_add doesn't generate correct result.

./example/conv2d_fwd_xdl_bias_relu_atomic_add 1 3 5

Perf: 1.3421 ms, 109.356 TFlops, 248.561 GB/s
error: 6.43832e+08
max_diff: 161.844, 32.7812, 194.625

**Comment by j4yan** [comment]
@asroy

**Comment by asroy** [comment]
@j4yan Please try ./example/conv2d_fwd_xdl_bias_relu_atomic_add 1 3 0

**Comment by j4yan** [comment]
@asroy That gave rise to correct results. 
Closing it.
